# Generated by Django 2.2.16 on 2020-12-28 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='posttagrelation',
            constraint=models.UniqueConstraint(fields=('tag', 'post'), name='unique_post_tag'),
        ),
    ]
