# Generated by Django 2.2.16 on 2020-12-30 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0002_auto_20201228_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(db_index=True, max_length=100, unique=True)),
                ('count', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='posttagrelation',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tag.PostTag'),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
