# Generated by Django 2.2.16 on 2020-12-17 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.SmallIntegerField(choices=[(0, 'Announcment'), (1, 'Article'), (2, 'Project'), (3, ' Academic')], db_index=True, default=1),
            preserve_default=False,
        ),
    ]
