# Generated by Django 2.2.16 on 2020-12-28 11:06

from django.db import migrations
import tag.fields


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=tag.fields.PostTagField(blank=True, null=True),
        ),
    ]
