# Generated by Django 2.2.16 on 2020-12-30 11:34

from django.db import migrations
import tag.fields


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20201228_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=tag.fields.PostTagField(blank=True, default=dict(Tag=[]), null=True),
        ),
    ]
