# Generated by Django 2.2.16 on 2021-01-09 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_auto_20201230_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='read_time',
            field=models.SmallIntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.IntegerField(default=1200),
            preserve_default=False,
        ),
    ]
